version: '3.9'
services:
  node:
    image: 'node:latest'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - '8080:8080'
    command: 'npm start'
    networks:
      - services

networks:
  services:
    external: true
