version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    networks:
      - services

networks:
  services:
    external: true
